### ISSUE TITLE
Should drop the 'npm-shrinkwrap.json' file (it messes up downstream)

### ISSUE THREAD

**Issue by pdcastro** [hertzg/node-net-keepalive#26]
> https://docs.npmjs.com/configuring-npm/shrinkwrap-json.html
> The recommended use-case for npm-shrinkwrap.json is applications deployed through the publishing process on the registry: for example, daemons and command-line tools intended as global installs or devDependencies. ***It’s strongly discouraged for library authors to publish this file, since that would prevent end users from having control over transitive dependency updates.***

My app is a command-line tool: https://github.com/balena-io/balena-cli/
We have a `npm-shrinkwrap.json` file, as recommended above. We include `net-keepalive` as a dependency. In a **production** install of my app, I have observed that `net-keepalive` installs some 200MB of dev dependencies -- some 285 dependencies, including for example `typescript` (53MB), `react-frame-component` (43MB) and `prettier` (10MB):

```
$ npm install --global --production balena-cli
$ cd ~/.nvm/versions/node/v12.18.2/lib/node_modules/balena-cli/node_modules/net-keepalive/node_modules/
$ du -hs .
199M    .
$ ls -l | wc -l
     287
$ du -hs * | grep M
53M    typescript
43M    react-frame-component
10M    prettier
9.1M    brace
7.6M    ffi-napi
7.4M    core-js
6.7M    core-js-pure
6.4M    @babel
4.8M    lodash
4.8M    sinon
3.1M    es-abstract
2.4M    ref-napi
2.2M    react-ace
1.8M    jsdoc
1.8M    mocha
1.5M    clean-css
1.7M    recast
1.2M    @sinonjs
1.1M    better-docs
```

So **the problem** is that `net-keepalive` is causing its own direct and indirect dev dependencies to be installed in production installs downstream (in apps like `balena-cli`), and unnecessarily taking a lot of disk space (200MB) on end users' machines.

I suspect it is because `net-keepalive` publishes the `npm-shrinkrap.json` file, which does not appear to be a recommended practice as quoted above. For example, `typescript` v3.9.6 is indeed listed in `net-keepalive`'s shrinkwrap file:
https://github.com/hertzg/node-net-keepalive/blob/v1.3.2/npm-shrinkwrap.json#L2928-L2933

Also, `net-keepalive`'s `package.json` file does not include a `files` section, which means that all files are published:

> https://docs.npmjs.com/files/package.json#files
> The optional files field is an array of file patterns that describes the entries to be included when your package is installed as a dependency. [...] ***Omitting the field will make it default to ["\*"], which means it will include all files.***

Having a `npm-shrinkwrap.json` file and not publishing it would probably only mask any issues. Similarly, a `package-lock.json` file ([also not recommended for libraries](https://docs.npmjs.com/configuring-npm/package-lock-json.html)) would only mask any issues (the issues would not appear in the `node-net-keepalive` repo, but would appear in downstream projects like `balena-cli`). How bad would it be to simply `git rm` the `npm-shrinkwrap.json` file? :-)  I understand that this would mean that any of `net-keepalive`'s own dependencies could change and cause `net-keepalive` to "break" at any time, but the way to avoid this is to include a `npm-shrinkwrap.json` file in downstream applications like `balena-cli`, not in libraries like `net-keeaplive`. Libraries simply cannot avoid living in a perilous, unstable world of dependencies. :-) This is my understanding.

And after all this complaining / lecturing, :-) let me end with: awesome project! 😁   Thank you very much for creating and maintaining it, and for considering the improvement suggested in this issue! 👍  🚀  😀

**Comment by hertzg** [comment]
Hello @pdcastro , Thanks for opening an issue and I'm supper happy that you find this package useful.

I totally agree that dev dependencies should not be installed on prod builds, you have correctly mentioned the `npm-shrinkwrap.json` exists to avoid dependency issues.

In the initial versions (back when node v0.10 was a thing) our dependencies were "not stable" and I had to introduce some kind of mechanism to keep things locked down.

I would like to help with slimming down the package for sure and I do not have strong feelings towards `npm-shrinkwrap`, it has caused its own issues for me as well. I just want to maintain some sanity with dependencies.

One thing that comes to mind is to just use exact version in `package.json` instead of `^`s but that would not lock the dependenceis of dependencies and those could break (even thou that should not be technicall `net-keepalive`'s responsibility).

Let me have a look into this, I certanly **do not** find it acceptable that prod builds include dev dependencies... I'll run some sizing tests and report back the result.

**Comment by hertzg** [comment]
So I did some quick lookup and apparently I somehow missed the recommendation of not using shrinkwrap for libs back in 7d7de4975896450cd1817dece6bf2c897965dc7b (Jan 28, 2016).

Indeed `npm-shrinkwrap.json` contains some (weird) dev depenendencies :man_facepalming:. One way to keep shrinkwrap without it including devDepdendency chain is to prune the non prod depenencies with `npm prune --production` which will update the `package-lock.json` with only prod dependencies and then rename it with `npm shrinkwrap`. The result is only locked down **prod** dependencies.

The problem with this is that it seems very hacky and also every time I run `npm install` the shrinkwrap keeps bloating so I for now I have removed the shrinkwrap file and I'll try to have faith in downstream dependencies following correct semver. I have faith that `ffi-napi` (@addaleax) would be the best person to keep its own dependencies in check :relaxed: 


> Also, net-keepalive's package.json file does not include a files section, which means that all files are published:
Instead of `files` property in `package.json` I maintain `.npmignore` which serves same purpose of keeping unrelated files out of the final package.

I've created a PR with more info addressing the size issues in #27 it should drop the installed size from `203mb` to `12mb` and not contain any dev dependencies unless specifically requested.

**Comment by hertzg** [comment]
Fixed in v1.3.3

```
$ npm i --production net-keepalive@1.3.2
...
$ du -hs ./node_modules/
203M	./node_modules/
```
vs
```
$ npm i --production net-keepalive@1.3.3
...
$ du -hs ./node_modules/
12M	./node_modules/

```

**Comment by pdcastro** [comment]
Thank you very much for quickly acting on this issue @hertzg ! 🏅 
It has made a massive difference in disk usage for `balena-cli`. 🎉

**Comment by hertzg** [comment]
@all-contributors please add @pdcastro for bug
